### PR TITLE
Billing221update android x

### PR DESCRIPTION
**Pull request by PiTi2k5**
Update to Xamarin Essentials instead of CurrentActivityPlugin

### CODE REVIEW

**Comment by EmilAlipiev** [comment]
Do you not need MainApplication.cs if you use Xamarin.Essentials? it was merged probably from CurrentActivityPlugin. I havent tried it yet but probably it works same way, not?

**Comment by PiTi2k5** [comment]
It should work without MainApplication.cs, you need only the xamarin.essentials init call in MainActivity.cs but i havent tried it on xamarin forms projects only in xamarin.android and it runs without issues.

**Comment by PiTi2k5** [comment]
Xamarin.Forms (Android part) project checked with live purchase, it runs fine.

**Comment by EmilAlipiev** [comment]
new version published with Essentials. you can test it https://www.nuget.org/packages/XFInAppBilling/2.0.3-beta

**Pull request merged**
